LOCAL_PATH := $(call my-dir)


include $(CLEAR_VARS)
LOCAL_SRC_FILES := asp.cpp
LOCAL_MODULE := libshim_asp
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_PROPRIETARY_MODULE := true
include $(BUILD_SHARED_LIBRARY)



include $(CLEAR_VARS)
LOCAL_SRC_FILES := egl.cpp
LOCAL_SHARED_LIBRARIES := libm libgcc
LOCAL_MODULE := libshim_egl
LOCAL_PROPRIETARY_MODULE := true
include $(BUILD_SHARED_LIBRARY)



## libshim_GUI
include $(CLEAR_VARS)
LOCAL_SRC_FILES := gui.cpp
LOCAL_SHARED_LIBRARIES := libgui
LOCAL_MODULE := libshim_gui
LOCAL_PROPRIETARY_MODULE := true
include $(BUILD_SHARED_LIBRARY)

